# All Settings

organization:
  name: "Energy Biosciences Institute"
  url: #{root_path}
  logo_file: "logo-ebi.png" 

site_identification_markup: "<strong>BETY</strong>db <small><strong>Biofuel Ecophysiological Traits and Yields </strong>Database</small>"

# Footer

footer_background_image_file: "logo-ebi-footer.jpg"

## Contact Information
admin_phone: "(520) 621-4381"
admin_email: "dlebauer@arizona.edu" # a test

citation_license_copyright_markup:

  '<p>LeBauer, David, Rob Kooper, Patrick Mulrooney, Scott Rohde, Dan Wang, 
  Stephen Long, Michael Dietze, (2017). BETYdb: A yield, trait, and ecosystem 
  service database applied to second‐generation bioenergy feedstock production.
  GCB Bioenergy. doi:10.1111/gcbb.12420</p>

  <p>All public data in BETYdb is made available under the <a
  href="http://opendatacommons.org/licenses/by/1-0/">Open Data Commons
  Attribution License (ODC-By) v1.0.</a> You are free to share, create, and
  adapt its contents.  Data with an access_level field and value &lt;= 2 is not
  covered by this license but may be available for use with consent.</p>

  <p>Copyright © 2010-2014 Energy Biosciences Institute</p>'

sponsors:
    - URL: http://illinois.edu
      title: "University of Illinois at Urbana-Champaign"
      text: "University of Illinois at Urbana-Champaign"
      logo_file: logo-illinois.png
      width: 246px
    - URL: http://www.berkeley.edu
      title: "University of California, Berkeley"
      text: "University of California, Berkeley"
      logo_file: logo-berkeley.png
      width: 145px
      additional_styling: "margin-left: 20%"
    - URL: http://www.lbl.gov
      title: "Lawrence Berkeley National Laboratory (LBL)"
      text: "Lawrence Berkeley National Laboratory"
      logo_file: logo-lbl.png
      width: 232px
    - URL: http://www.bp.com
      title: "British Petroleum (BP)"
      text: "British Petroleum (BP)"
      logo_file: logo-bp.png
      width: 54px
      additional_styling: "margin-right: 40%"

# Home Page

homepage_heading: "Welcome to BETYdb"

homepage_body:

  lead_text:

    BETYdb supports the synthesis and modeling of plants and ecosystems.

  marked_up_block_text:

    <strong
    class="green">BETYdb</strong> has been developed to support research,
    agriculture, and policy by synthesizing available information on potential
    biofuel crops. 
    It is now used widely by the crop and ecosystem modeling communities.
    The motivation for creating BETYdb was to develop biofuel crops
    in an ecologically and economically sustainable way. This requires evaluating 
    the growth and functionality of current and potential biomass crops from local
    to global scales. 

  photo:

    file: miscanthus.jpg

    alt_text:

      Photo by L. Brian Stauffer, 
      provided by University of Illinois at Urbana-Champaign

# Miscellaneous

## This affects both the home page and the footer. Mostly used to turn off maps of crop model predictions that are in betydb.org:
show_crop_map_links: false

# Override this with a secret key to run a secure site:
rest_auth_site_key: 'your secret key'

# Note: If your site is not public (e.g., you are a developer), it is better
# to use the default site key and not override it here.  This is because if you
# use the default site key, the caryaXX and guestuser account passwords will
# work out of the box.

production:
    rest_auth_site_key: 'some moderately long, unpredictable text'
