# To use this file for a terraref BETYDb Web site:
# 1. Copy this file to config/application.yml
# 2. Replace the dummy value of rest_auth_site_key with the key appropriate to your site
# 3. Make any other tweaks you deem appropriate
# 4. Save the file and restart your BETYdb server

# Contact Information
admin_phone: "(520) 621-4381"
admin_email: "dlebauer@arizona.edu"

# Override this with a secret key to run a secure site:
rest_auth_site_key: 'your site's secret key'


schema_spy_settings:
    java_executable: /usr/java/jre1.8.0_91/bin/java
    postgresql_driver_jar_file: lib/tasks/jar/postgresql-9.4.1208.jre7.jar
    settings_for_customized_documentation:
        schema_spy_jar_file: lib/tasks/jar/schemaSpy.jar
        output_directory: .
        remove_root_dir_files: true

organization:
  name: ""
  url: #{root_path}
  logo_file: "custom/terraref-logo.png"

site_identification_markup: "<strong>BETY</strong>db <small><strong>TERRA-REF Phenotype</strong> Database</small>"


# Footer

footer_background_image_file: "custom/mac_sorghum.jpg"

citation_license_copyright_markup:

  <p>The TERRA Reference phenotyping data is being published and is being released on a rolling basis, based in part on requests.

sponsors:
    - URL: https://arpa-e.energy.gov/
      title: "ARPA-E"
      text: "ARPA-E"
      logo_file: custom/arpa-e-logo.png
      width: 162px
    - URL: http://energy.gov/
      title: "U.S. Department of Energy"
      text: "U.S. Department of Energy"
      logo_file: custom/doe-logo.png
      width: 152px
      additional_styling: "margin-left: -20%"


# Home Page

homepage_heading: "Welcome to TERRA REF phenotype database"

homepage_body:

  lead_text:

    Reference traits from high throughput sensing platforms

  marked_up_block_text:
  
     <p>This is the trait database for the TERRA-REF phenotyping project. 
     TERRA-REF developed reference datasets and software to advance the science of crop breeding. 
     This database contains plant and plot-level trait data such as plant height, biomass, leaf area, transpiration, phenology, water use efficiency, and biomass yield, 
     as well as experimental metadata, plot polygons, and genotype information. 
     Trait (phenotype) data include both hand measured and sensor derived measurements
     See the project website <a href="http://terraref.org" target="_blank">terraref.org</a> for more information about our project, 
     including links to sensor data, information about our phenomics pipeline, and documentation.</p>

     <p>Summaries of available data can be found on a separate website, <a href="https://terraref.org/traitvis" target="_blank">https://terraref.org/traitvis</a>.</p>

     <p>Published data are on Dryad. This database can also be accessed via the R traits package, a local copy of the database, or via the BETYdb or BrAPI APIs.</p>     

  photo:

    file: https://terraref.org/sites/terraref.org/files/TERRA-REF-Scanner.jpg

    alt_text:

      Photo of the Lemnatec Field Scanner with Sorghum. Credit: Rick Ward

  search_placeholder_text: "EX: Sorghum MAC"

# Miscellaneous

## This affects the home page, the menu, and the footer:
show_crop_map_links: false
